### ISSUE TITLE
建议.....

### ISSUE THREAD

**Issue by particledream78** [forpdown/pdown#1]
如果在 Folder Tree 的右边,，直接加上和显示每个文件的下载进度，就更加完美。而不是像现在一样，分析完之后，按下 “下载选中的文件” 按钮后，Folder Tree 不显示了，所有新任务下载都变成单一显示，无法看到整个 Folder 的下载进度，和 Folder 里面的文件下载进度。希望作者明白我的说法。。。。。只是建议，希望不要介意。。。。。

**Comment by forpdown** [comment]
我明白你的意思，但是逻辑上不可以

1 filetree只是显示链接内的文件，此时并没有去拉取，我没去下载
2 你勾选文件以后，只是把文件加入到下载列表，此时没有去拉取
3 当一个任务启动，显示拉取中（xx秒），此时服务器才会受到命令去拉取这一个文件
4 文件是分片拉取的，一般是下载到20MB左右开始传输给你
5 当你点击暂停，服务器的拉取也会立即停止，等你下一次点击继续时，服务器会重新启动拉取

如上，逻辑上，服务器并不知道文件的拉取进度，所以也无法在filetree显示进度
