### ISSUE TITLE
联网解析时无法连接到服务器

### ISSUE THREAD

**Issue by drb0** [forpdown/pdown#1]
大概有两天了，联网解析时无法连接到服务器，解析失败，进度：连接服务器中。

**Comment by ruoyin520** [comment]
无法连接到服务器，可能是正在维护中！

**Comment by drb0** [comment]
原来如此~  作者dalao辛苦啦~  注意安全，谨防重蹈PDL覆辙~  再次感谢之前带来的便利~

**Comment by drb0** [comment]
> 无法连接到服务器，可能是正在维护中！

你看看[主页](https://github.com/forpdown/pdown)，往下拉
黑色的大字小字已经写出原因啦~
伙伴再会~
寻找下一个convenience吧~
