### ISSUE TITLE
文件大小限制的建议

### ISSUE THREAD

**Issue by pmkol** [forpdown/pdown#11]
是否可以根据扩展名，限制文件的大小，比如默认500M，像ISO一类的镜像文件，可以不受限制，但下载次数限制一下，因为有时候下载一些ISO，在网盘下载速度会快的多，建议作者可以考虑下，最后感谢付出

**Comment by forpdown** [comment]
你好
不想这么麻烦，扩展名可以随意改，这个操作起来作用不大。并且，不同的人需要下载的文件不同所以扩展名区别对待也不太合适，限制细则太多会让人很反感
