### ISSUE TITLE
v3.04.06 版，最大支持下载的文件体积变成 1500 MB 了

### ISSUE THREAD

**Issue by wordlessmiracle** [forpdown/pdown#13]
中午下载的时候突然发现，v3.04.06 版的 PDown 最大支持下载的文件体积从 500 MB 变成 1500 MB 了。

![image](https://user-images.githubusercontent.com/63574166/85514806-001f7080-b62f-11ea-9e7f-699dcc8d9a9f.png)

不过软件顶部的说明和更新日志里都没有提到这一点。
想问一下是作者修改了使用限制还是手抖敲错了。
前者的话，希望作者能补上更新日志，修改软件里相应的描述；后者的话，作者尽快改回来？（怕被薅秃）

**Comment by forpdown** [comment]
你好，是下载限制不断在更新，在能力范围内我也不想大家限制那么多，

客户端只有等下个版本更新时才能修改描述。所以习惯性就不更新这里了，会一直显示500MB

**Comment by forpdown** [comment]
备注一下，跟版本没关系，v3.4.5,v3.4.4 也是一样的1.5G
再备注一下，v3.4.4刚发布的时候（6月13日）就是1G了
