### ISSUE TITLE
下载到一半没有速度怎么回事呢

### ISSUE THREAD

**Issue by wanfengyingxiu** [forpdown/pdown#14]
重启也不好用。另外我下的是600m的文件，是因为这个原因吗？

**Comment by forpdown** [comment]
你好

一般就是不能下载，可能是程序BUG导致，
下载速度属于网络原因，遇到下载到一半就没速度，我也不知道是为什么，所以帮不到你，只能跟你说换个时间再试试

**Comment by forpdown** [comment]
跟600MB完全一点关系没有，可能跟这个文件有关，就是换个其他的文件就没事了

我能想到的就是，比如你下载600M需要5分钟，在第3分钟的时候，这个链接被取消分享/文件被删除/文件被404，这个时候就无法继续下载了
