### ISSUE TITLE
请问一下有没有这样的115项目？

### ISSUE THREAD

**Issue by jiujiwuan** [forpdown/pdown#15]
115会员应该可以无限制下载，这样的话，大家提供链接就可以实现下载了。

**Comment by forpdown** [comment]
抱歉我也不知道

**Comment by pw-fxy** [comment]
115？不好意思我不太懂，抱歉





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pdown"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 下午5:19
收件人:&nbsp;"forpdown/pdown"<pdown@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [forpdown/pdown] 请问一下有没有这样的115项目？ (#15)





 
抱歉我也不知道
