### ISSUE TITLE
建议。。。关于下载

### ISSUE THREAD

**Issue by miuicat** [forpdown/pdown#2]
现在下载文件夹时候，如果我下载中途取消了下载，本地还是会有一个空文件夹留存，能不能删除下载时候同步删除本地空文件夹（就是我取消下载时候）

**Comment by forpdown** [comment]
好的，下次更新的时候会修正此BUG，是我没考虑到

**Comment by miuicat** [comment]
> 好的，下次更新的时候会修正此BUG，是我没考虑到

文件下载大小限制后续会不会提升？比如1GB或者更高，单个文件只能500MB的话，感觉好多文件都下载不了啊大佬。感谢

**Comment by miuicat** [comment]
文件下载大小限制后续会不会提升？比如1GB或者更高，单个文件只能500MB的话，感觉好多文件都下载不了啊大佬。感谢
