### ISSUE TITLE
如何获取我搜索出来的文件的网盘链接？

### ISSUE THREAD

**Issue by Walden1976** [forpdown/pdown#3]
如题，谢谢

**Comment by pdown2020** [comment]
没办法，某些事件原因是用户隐私，链接可能会涉及到用户隐私，为了防万一，直接屏蔽

**Comment by pdown2020** [comment]
你可以先下载，然后自己上传到自己的网盘，创建新的分享链接

**Comment by forpdown** [comment]
你可以先下载，然后上传到自己的网盘，创建新的分享链接

**Comment by Walden1976** [comment]
主要是软件超过500M就不能下载了，我是想获取网盘后用其他方法下载大尺寸文件。

**Comment by forpdown** [comment]
那就不行了，用户隐私问题，不支持提取

**Comment by miuicat** [comment]
> 那就不行了，用户隐私问题，不支持提取

考虑增大下载文件大小吗？

**Comment by Giancarlo-Ma** [comment]
code可以贴出来吗

**Comment by forpdown** [comment]
1 没考虑过增大文件大小
2 code去原github看
