### ISSUE TITLE
更新方式

### ISSUE THREAD

**Issue by L-GROSS** [forpdown/pdown#4]
为啥不直接把文件提交到github上来啊   直接用git更新就好了啊

**Comment by L-GROSS** [comment]
每次都需要下压缩包 然后又解压  感觉有点小麻烦

**Comment by xzkeee** [comment]
作为新手的我反而这种原始的更新方式比较直白hhhh

**Comment by forpdown** [comment]
大部分人并不知道什么是github，所以更加不知道什么是git，我自己也不用git的，直接是网页版github
