### ISSUE TITLE
兄弟 要不算了吧

### ISSUE THREAD

**Issue by cexll** [forpdown/pdown#6]
其实我们都不做第三方客户端
时间久一点 慢慢的人们就不会怎么用百度网盘了
推荐作者去用蓝奏云 或者去看看 https://github.com/xausky/DockerRegisterCloud

**Comment by forpdown** [comment]
厉害

**Comment by rrq0514** [comment]
PDown是个好工具，就是限量2G，开发成无限的就爽了
