### ISSUE TITLE
什么都没有下载一直显示流量限制请明天在试

### ISSUE THREAD

**Issue by DINGDOM** [forpdown/pdown#8]
> 

-

**Comment by DINGDOM** [comment]
![image](https://user-images.githubusercontent.com/46958480/85309061-a1e67680-b4e4-11ea-94b2-f3c7c5b19ca3.png)

**Comment by forpdown** [comment]
你好 可能是程序BUG，误判了。暂时没有修正方案

**Comment by forpdown** [comment]
每人每天2GB流量限制，是根据你的电脑计算出一个硬件码，根据这个码去判断你今天下载了多少流量（就比如身份证），但实际操作中发现，不同的电脑有几率出现相同的硬件码。此时就会导致误判，某个人跟你的硬件码一样时，某个人先下载会导致你流量限制，反过来你先下载也会导致某个人流量限制

硬件码重复几率很小，并且我也没有其他的好的方式去限制，所以出现这个BUG，我也无法修复
